### ISSUE TITLE
TODO: Let's test the limit of our ability xD

### ISSUE THREAD

**Issue by itsmenewbie03** [itsmenewbie03/project-rapport#47]
# TODO

- [ ] improve UI (remove unwanted elements, fill the sceen deez nuts)
- [ ] add name and contact number as optional fields
- [ ] compensate for the Model Accuracy (use HD camera, check for optimizations, read the docs)
- [ ] clean the images after submit
- [ ] add overall emotion summary in each feedback/evaluation (in history page)
